spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mapbook-db.cdj9jjrgjane.ap-northeast-2.rds.amazonaws.com:3306/test
    username: admin
    password: mapbookadmin
#    username: root
#    password: wnsdud12!@
#    url: jdbc:mysql://localhost:3306/library_service

elasticsearch:
  host: localhost
  port: 9200

  redis:
    port: 6379

resilience4j:
  circuitbreaker:
    instances:
      getMapBooks:
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 10
        slidingWindowType: COUNT_BASED

#data4:
#  bookExist:
#    api:
#      url: http://data4library.kr/api/bookExist
#      authKey: 0f6d5c95011bddd3da9a0cc6975868d8293f79f0ed1c66e9cd84e54a43d4bb72
#      format: json