logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE=TRACE:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://localhost:3306
  jpa:
    hibernate:
      ddl-auto: none

  data:
    elasticsearch:
      cluster-nodes=localhost:9200:

elasticsearch:
  host: localhost
  port: 9200

data4:
  bookExist:
    api:
      url: http://data4library.kr/api/bookExist
      authKey: 0f6d5c95011bddd3da9a0cc6975868d8293f79f0ed1c66e9cd84e54a43d4bb72
      format: json