spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wnsdud12!@
    url: jdbc:mysql://localhost:3306/library_service
  jpa:
    hibernate:
      ddl-auto: none

elasticsearch:
  host: localhost
  port: 9200

data4:
  bookExist:
    api:
      url: http://data4library.kr/api/bookExist
      authKey: 0f6d5c95011bddd3da9a0cc6975868d8293f79f0ed1c66e9cd84e54a43d4bb72
      format: json

#resilience4j:
#  retry:
#    configs:
#      default:
#        maxRetryAttempts: 2
#        waitDuration: 5
#        ignoreException:
#          - java.util.NoSuchElementException
#    instances:
#      getAccessToken:
#        baseConfig: default
#        maxRetryAttempts: 3

#
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        failureRateThreshold: 50
#        slowCallRateThreshold: 100
#        slowCallDurationThreshold: 60000
#        permittedNumberOfCallsInHalfOpenState: 4
#        maxWaitDurationInHalfOpenState: 1000
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        waitDurationInOpenState: 10000
#    instances:
#      customCircuitBreaker:
#        baseConfig: default